#!/usr/bin/sh

ps aux | egrep -i 'python3' | egrep debpakir
if [[ $? == 0 ]]; then
pgrep -f debpakir$ && /usr/bin/xdotool key --window "$(/usr/bin/xdotool search --name "^debpakir$")" R && exit
else
exec /usr/bin/python3 /usr/share/daft-8/debpakir/src/main.py "$@"
fi
